version: "3.8"

services:

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"
    shm_size: 2gb

  selenium-test:
    build: .
    container_name: selenium-testcase-container
    depends_on:
      - selenium
